name: Collect EPL sources (every 30m)

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes (UTC)
  workflow_dispatch: {}

jobs:
  collect:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci || npm i
      - name: Run collector
        run: npm run collect
      - name: Ensure file exists (even if 0 items)
        run: |
          mkdir -p public/data
          test -f public/data/latest.json || echo '{"match":{},"items":[]}' > public/data/latest.json
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/latest.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update latest.json [CI]"
            git push
          else
            echo "No changes"
          fi
